#
# Module manifest for module 'Laser'
#
# Generated by: POC: Lt. Ryan Rickert
#
# Generated on: 1/14/2015
#

@{

# Script module or binary module file associated with this manifest
ModuleToProcess = ''

# Version number of this module.
ModuleVersion = '1.0'

# ID used to uniquely identify this module
GUID = 'bb9637ec-9390-4f20-87a0-4116b62bc1d3'

# Author of this module
Author = 'POC: Lt. Ryan Rickert'

# Company or vendor of this module
CompanyName = '92 IOS'

# Copyright statement for this module
Copyright = 'USAF'

# Description of the functionality provided by this module
Description = 'A Torch-like series of modules that use WMI as the primary vehicle for host endpoint querying'

# Minimum version of the Windows PowerShell engine required by this module
PowerShellVersion = ''

# Name of the Windows PowerShell host required by this module
PowerShellHostName = ''

# Minimum version of the Windows PowerShell host required by this module
PowerShellHostVersion = ''

# Minimum version of the .NET Framework required by this module
DotNetFrameworkVersion = ''

# Minimum version of the common language runtime (CLR) required by this module
CLRVersion = ''

# Processor architecture (None, X86, Amd64, IA64) required by this module
ProcessorArchitecture = ''

# Modules that must be imported into the global environment prior to importing this module
RequiredModules = @()

# Assemblies that must be loaded prior to importing this module
RequiredAssemblies = @()

# Script files (.ps1) that are run in the caller's environment prior to importing this module
ScriptsToProcess = @()

# Type files (.ps1xml) to be loaded when importing this module
TypesToProcess = @()

# Format files (.ps1xml) to be loaded when importing this module
FormatsToProcess = @()

# Modules to import as nested modules of the module specified in ModuleToProcess
NestedModules = 'Deploy-Antibody.ps1', 'LaserFunctions.psm1', 'server-loop.ps1', 'Enum-ProcessWMI2.ps1', 'Enum-ProcessWMI.ps1', `
                'Enum-AutorunWMI.ps1', 'Enum-DriverWMI.ps1', 'Enum-ServiceWMI.ps1', 'Enum-EventsWMI.ps1', 'Enum-NetworkStatisticsWMI.ps1', `
                'Enum-NetworkLogonWMI.ps1','Enum-logonWMI.ps1'

# Functions to export from this module
FunctionsToExport = '*-*'

# Cmdlets to export from this module
CmdletsToExport = '*'

# Variables to export from this module
VariablesToExport = '*'

# Aliases to export from this module
AliasesToExport = '*'

# List of all modules packaged with this module
ModuleList = @()

# List of all files packaged with this module
FileList = @()

# Private data to pass to the module specified in ModuleToProcess
PrivateData = ''

}